apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Publish action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  version: 0.0.1
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Configure container registry
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: index.docker.io # or docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and publish container image
        uses: cloudbees-io/kaniko@v1
        with:
          destination: ${{ vars.DOCKERHUB_USERNAME }}/kestra-action:${{ env.version }}